### ISSUE TITLE
Javascript error: unable to find icon.ico

### ISSUE THREAD

**Issue by Sanyam02** [BlocklyDuino/BlocklyDuino2Electron#4]
![image](https://user-images.githubusercontent.com/68013436/90550103-1bc97200-e1ad-11ea-852e-bdaf14e0a47d.png)

image could not be created from icon.ico.

Process followed as mentioned in the repository still unable to build it.

**Comment by SebCanet** [comment]
Yeah, quite strange...even if you launch it again?
It's on the TODOlist...

**Comment by Sanyam02** [comment]
Yes did it multiple times and even had cleared everything and started over. But facing the same issue.
If you could let me know how to find it on my end or if can help me with remote assistance.

**Comment by SebCanet** [comment]
When you launch the exe Windows version, there's no pb. You have to comment/uncomment lines in main.js files, and also in html files, if you want to launch it from npm command line.
